### ISSUE TITLE
Elasticsearch disk usage failure in SRM staging

### ISSUE THREAD

**Issue by akariv** [whiletrue-industries/srm-devops#13]
I'm getting this error from ES when trying to index
[TOO_MANY_REQUESTS/12/disk usage exceeded flood-stage watermark, index has read-only-allow-delete block];')

**Comment by akariv** [comment]
Found a workaround to disable the check on elasticsearch using this:
https://stackoverflow.com/questions/30289024/high-disk-watermark-exceeded-even-when-there-is-not-much-data-in-my-index

Still needs to be resolved as it's probably affecting other es instances on the cluster as well.

The command I used:
```
PUT /_cluster/settings
{
  "persistent": {
    "cluster.routing.allocation.disk.threshold_enabled": true,
    "cluster.routing.allocation.disk.watermark.low": "4g",
    "cluster.routing.allocation.disk.watermark.high": "2g",
    "cluster.routing.allocation.disk.watermark.flood_stage": "1g",
    "cluster.info.update.interval": "5m" 
  }
}
```

**Comment by OriHoch** [comment]
open-bus DB is quickly using up all the disk space.. I will move it to dedicated storage so it won't affect other workloads

**Comment by OriHoch** [comment]
hasadna/open-bus#383

**Comment by OriHoch** [comment]
done, available disk space: 183GB (39%)

**Comment by akariv** [comment]
Also adding here as note to self - to release blocked indexes you need to call:
```
PUT /_all/_settings
{
   "index.blocks.read_only_allow_delete": null
}
```
