### ISSUE TITLE
add retry in ci script

### ISSUE THREAD

**Issue by OriHoch** [whiletrue-industries/srm-devops#4]
some actions fail temporarily but will succeed later, we should have a retry mechanism in relevant places:
* https://github.com/whiletrue-industries/srm-devops/runs/3772143959?check_suite_focus=true
* https://github.com/whiletrue-industries/srm-devops/runs/3775098222?check_suite_focus=true

**Comment by akariv** [comment]
Yes, I've noticed that too...

Is there a simple way to detect temporary failures vs. permanent ones?
Or should we just retry always if failed?
